// apps/app-blog/src/App.tsx
import React from "react";
import ReactDOM from "react-dom";

import "./index.scss";

const App = () => (
  <div className="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: app-blog</div>
    <div>Framework: react</div>
    <div>Language: TypeScript</div>
    <div>CSS: Tailwind</div>
  </div>
);

export default (el) => {
    ReactDOM.render(<App />, el);
}

// apps/app-store/src/App.vue
<template>
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <div>Name: app-store</div>
    <div>Framework: vue3</div>
    <div>Language: TypeScript</div>
    <div>CSS: Tailwind</div>
  </div>
</template>

<script lang="ts">
  import { defineComponent } from 'vue'

  export default defineComponent({});
</script>
